#!/usr/bin/env python3

import boto3
from datetime import datetime, timedelta 

def lambda_handler(event, context):
    """run in lambda"""
    runSnapshot()
  
def runSnapshot():
    """ Find all istances to backup and snapshot"""
    ec2 = boto3.client('ec2')
    reservations = ec2.describe_instances(
        Filters=[
            {'Name': 'tag-key', 'Values': ['backup', 'Backup']},
        ]
    )['Reservations']
    
    instances = sum(
        [
            [i for i in r['Instances']]
            for r in reservations
        ], [])
    
    for instance in instances:
        for dev in instance['BlockDeviceMappings']:
            if dev.get('Ebs', None) is None:
                # skip non-EBS volumes
                continue
            vol_id = dev['Ebs']['VolumeId']
    
            snapshot = ec2.create_snapshot(
                VolumeId=vol_id,
            )
            ec2.create_tags(
                Resources = [snapshot['SnapshotId']],
                Tags = [ 
                    {'Key': 'autosnap','Value': 'True'},
                    {'Key': 'deleteOn','Value': str(datetime.now()+timedelta(days=30))},

                ]
            )
    
if __name__ == '__main__':
    """ Run in shell """
    runSnapshot()

